### ISSUE TITLE
Environment configuration for tests

### ISSUE THREAD

**Issue by mfw78** [itsahedge/go-cowswap#41]
**Problem**
Currently the environment variables require the `PRIVATE_KEY` AND `ETH_ADDRESS` to be configured. `ETH_ADDRESS` is redundant as this may be inferred from the `PRIVATE_KEY`.

**Solution**
Only use `PRIVATE_KEY` and determine the `ETH_ADDRESS` from such.

**Tasks**

- [ ] Remove `ETH_ADDRESS` GetEnv throughout code.
- [ ] Set `EthAddress` in `ConfigOpts` from calculated address from `PRIVATE_KEY`.
- [ ] Update docs / examples.
